### ISSUE TITLE
Use a pre-existing Elasticsearch instance

### ISSUE THREAD

**Issue by obones** [SEPIA-Framework/sepia-docs#146]
I'm trying to install SEPIA following the [Quick start](https://github.com/SEPIA-Framework/sepia-installation-and-setup#quick-start) instructions but because I already have an ElasticSearch engine running on my server, I directly tried option 1 in `setup.sh` 
Sadly, it fails with this error message:

```
Preparing Elasticsearch:
2021-12-21 11:21:41 ERROR - deleteAny - ElasticSearch - error in '_all': {"code":-1,"error":"java.net.ConnectException: Connexion refusée (Connection refused)","HTTP_REST_SUCCESS":false}
```

My ES Server is running on the default port (9200) and is responding just fine to various other clients.
How can I tell the setup script to use my currently running instance?

**Comment by fquirin** [comment]
Careful! The setup will clear the whole database first to make sure there is no unwanted stuff left! :skull_and_crossbones: ... so I guess you might have been lucky here ^^ :sweat_smile: (I've just added a note to the option).

SEPIA Elasticsearch is running on port 20724.
There is a specific version required as well unfortunately because Elasticsearch 6.x.x had some breaking changes.

**Comment by obones** [comment]
Well, it stopped directly because my existing instance is not running on the 20724 port, so yes, I was lucky.
I understand the prerequisite about a specific version, I'll use this one then.
