### ISSUE TITLE
Cannot change user roles

### ISSUE THREAD

**Issue by Smarthome-Creator** [SEPIA-Framework/sepia-docs#17]
Hi there,
first of all I want to congratulate you on this great project. Great job so far.
I wanted to add the role smarthome guest to a user, but unfortunately that is not possible.
You write in the wiki that you should check the field ´Overwrite Roles´, but unfortunately that doesn't exist. :-(
I can assign roles but then all core roles are gone or I can't overwrite them. You can see it in the picture.
Excuse my english, it's not the best.
![core roles](https://user-images.githubusercontent.com/61153058/74686788-d82c8600-51d2-11ea-91c5-46d858935ada.JPG)
![no overwrite roles field](https://user-images.githubusercontent.com/61153058/74686853-132eb980-51d3-11ea-97a7-e50e6fc23bc6.JPG)

Best wishes

**Comment by fquirin** [comment]
Hello and thanks a lot :-)

The text was a bit out-dated and confusing because the roles field was called "Overwrite Roles" in an earlier version. I've updated the text now.

The error message you see actually refers to the "core accounts" (by default uid1003 and uid1005, aka 'superuser' and 'assistant') that cannot be modified. I assume you've recreated these users at some point (or changed the password again?) since it seems one of your core-accounts has the ID uid1009 now.

I strongly recommend to use the core-accounts only for configuration! To proceed please create a new user and edit it's rules as required.

cu,
Florian

**Comment by Smarthome-Creator** [comment]
Hello Florian,

thank you for your explanation. I now understand how role assignment works. In Germany we say: "Ich stand auf dem Schlauch!" ;-)

Thx for your help!

**Comment by sepia-assistant** [comment]
Aber gerne doch ;-)
