### ISSUE TITLE
sepia/home - Docker installation not working

### ISSUE THREAD

**Issue by SHU-red** [SEPIA-Framework/sepia-docs#175]
**Describe the bug**
I want to try out sepia
Therefore i followed the guide at https://hub.docker.com/r/sepia/home

**SEPIA client and server versions**
- SEPIA-Server version: v2.6.1_amd64 (Docker Image)

**To Reproduce**
1. perform the first steps of installation until "bash setup.sh" shall be performed from within the sepia docker container
2. setup.sh is not present in the /home/admin/SEPIA/-folder

**Expected behavior**
setup.sh is there and further installation steps can be performed

**Additional context**
Home-Server running on TrueNAS Scale
I have no knowledge in using Sepia by now

**Comment by SHU-red** [comment]
UPDATE:
Somehow i got the files created by using docker with cli-commands directly
Now the container is in an infinite bootloop
--> This means, that even if im already executing setup.sh, the container-execution stopps immediately

Can all of this be caused, just because im using bind-mount-directories and not defined docker-volumes?
I need to use bind-mounts because of the zfs-filesystem in TrueNAS SCALE ... otherwise this would cause a mess ..

During one single loop the following logs can be seen
```

Starting nginx: nginx.
/--------------------------------------------------------------------------------
| Instructions to run SEPIA as Docker container
| More info: https://github.com/SEPIA-Framework/sepia-docs/wiki/SEPIA-inside-virtual-environments
| 
| On your HOST (the machine that runs the Docker container) you need to increase
| virtual memory (mmap counts) for Elasticsearch via the command (Linux):
| - sudo sysctl -w vm.max_map_count=262144
| In Windows and Mac you might need to SSH into your Docker VM first, e.g. via
| - Mac (xhyve): screen ~/Library/Containers/com.docker.docker/Data/vms/0/tty
| - Windows (Docker Toolbox): docker-machine ssh
| The SEPIA Docker container will inherit this setting form the host.
| 
| Create an EMPTY Docker volume so that the container can copy persistent data (Linux example):
| - SEPIA_SHARE=/home/[my-user]/sepia-home-share && mkdir -p 
| - docker volume create --opt type=none --opt device= --opt o=bind sepia-home-share
| 
| On the first run use the terminal to finish the SEPIA setup, e.g.:
| - docker run --rm --name=sepia_home -it -v sepia-home-share:/home/admin/SEPIA sepia/home:vX.Y.Z /bin/bash
| - bash setup.sh  (steps 4 and 1)
| 
| Exit setup and terminal and use a default run command like this:
| - docker run --rm --name=sepia_home -p 20726:20726 -v sepia-home-share:/home/admin/SEPIA sepia/home:vX.Y.Z
\--------------------------------------------------------------------------------
openjdk version "11.0.14" 2022-01-18
OpenJDK Runtime Environment (build 11.0.14+9-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.14+9-post-Debian-1deb10u1, mixed mode, sharing)
Running: SEPIA Home v2.6.1
Running Elasticsearch 5.3.3
95
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Waiting for Elasticsearch on port 20724 ...
....
Connection found. Waiting for cluster health check (max. 60s) ...
Status YELLOW or GREEN: true
Elasticsearch is ready for action.
Checking Elasticsearch setup ...
Elasticsearch is NOT yet setup (or not running with default settings)! Run setup.sh first.
```

**Comment by SHU-red** [comment]
OK sorry for all of my self-talking here
It seems ive been getting to make the setup by just setting everything up via normal docker-cli

Afterwards i hope i can manage/set-up my sepia through portainer-stacks (docker-compose) properly

Thanks

**Comment by fquirin** [comment]
Hi @SHU-red 

some additional info that might be helpful to understand what was going on:

- The SEPIA files and folder structure isn't really optimal for Docker because the persistent assistant and user data (the stuff that gets backed-up during update) is currently not collected in one single place that could be used as (initially empty) shared folder. To avoid configuration headaches I've decided to simply put the whole SEPIA folder into one shared volume.
- If your shared volume is empty that means the container didn't copy the folder contents during start-up. Docker is supposed to do this automatically but it can fail if your volume wasn't empty (Docker will not overwrite files!) and might also be the case if you create the volume in other ways (yaml file? idk?). In theory you can simply extract the SEPIA-Home Zip file (release version) into the folder if Docker keeps refusing to write the data itself.
- The "infinite bootloop" probably happens when the folder is empty and the process never actually starts. Due to the 'restart' flag Docker will try again and again and fail each time.

I have to admit I'm not a big fan of running SEPIA inside of Docker at the moment. In its current state its more complicated to set up and maintain/update than simply installing Java and the hand full of basic Linux packages required to run SEPIA, but I get why its appealing to users especially when they manage containers from one central place (NAS etc.).

I think with some love the process could become much easier for example one could implement some checks for the empty SEPIA folder, use symlinks for the database folder etc. and run the setup before building the container. The user could then boot up the system right away and simply has to create a test user and change the default passwords for admin and assistant :thinking: .

**Comment by SHU-red** [comment]
Thank you very much!
