### ISSUE TITLE
Microsphone not accessible

### ISSUE THREAD

**Issue by RobSteward** [SEPIA-Framework/sepia-docs#202]
**Describe the bug**
Microphone blocked and unable to use voice on Android mobile app

**SEPIA client and server versions**
- Client OS: OnePlus LE2113 running Lineage Os 19-20220627 on Android 12
- SEPIA-Client version: v.024.2 - en - m-c
- SEPIA-Server version: v2.6.2

**To Reproduce**
1. Start server
2. Open mobile app
3. Try to say "Hi Sepia" or tab blue button
4. Get error "UI: Microphone has not been recognized properly or access was denied."

**Expected behavior**
Microphone access allowed and listening mode started

**Additional context**
* Normal function (aka menu navigation) and text input work.
* I've checked permissions and also reset them. The app is allowed to use the microphone:

https://user-images.githubusercontent.com/13047378/179981733-c08c47fb-1b42-4f8d-927c-35c09fe11792.mp4

**Comment by fquirin** [comment]
Hi Rob,

I remember there was a discussion about Lineage OS once with a similar problem. The reason was that Lineage OS has no `native` service for speech recognition integrated or it is disabled because it is bound to the (disabled? non-existing?) Google services. If ASR engine is set to native the service will throw an error if the app tries to use it.

Can you try the microphone setup in `settings -> media devices` just to see if the microphone in general is working? If the recording works but you can't hear anything try to set the gain to ~10 for a start.

If it works you can switch to the [SEPIA STT server](https://github.com/SEPIA-Framework/sepia-stt-server) as alternative and host your own, fully private speech recognition.

**Comment by RobSteward** [comment]
Fair enough. Can't have convenience and privacy :D.

Will look into setting up a `SEPIA SST server` at some point.

**Comment by fquirin** [comment]
> Can't have convenience and privacy :D

Well ... not quite yet 😅, but the STT server is getting better and easier to install with every update ^^.
The good microphones of modern smart phones help with the recognition quality as well, just be sure to run the mic setup once to find (and store) a good gain setting.

Technically it is even possible to run one of the STT engines on device but the user experience isn't very good on most devices yet and the app size increases from 5MB to 50MB :-|, so I'm not yet willing to include it for experimentation only.

It is probably fair to mention that Google Android STT is able to run offline, even on my old 2017 Samsung A3, but of cause you still don't know what they do with the data and you never really know which mode (online/offline) is active.
