### ISSUE TITLE
install java packages for smart-service

### ISSUE THREAD

**Issue by royrogermcfreely** [SEPIA-Framework/sepia-docs#204]
hello,

i am trying to create a smart-service with java.

for that i have to install the wolframalpha.jar from [wolfram-alpha-java-binding](https://github.com/aeurielesn/wolfram-alpha-java-binding)

i copied the jar file to the folling folders:
sepia-mesh-nodes/libs
sepia-assist-server/libs
sepia-teach-server/libs
sepia-websocket-server-java/libs

but when i try to import the needed files i get the following error:

``{` "result": "fail", "error": "ERROR: Class 'DynamicQuestionAnswering' - Compile errors: \nstring:///net/b07z/sepia/sdk/services/uid1007/DynamicQuestionAnswering.java - Line 20: package com.wolfram.alpha does not exist \nstring:///net/b07z/sepia/sdk/services/uid1007/DynamicQuestionAnswering.java - Line 21: package com.wolfram.alpha does not exist \nstring:///net/b07z/sepia/sdk/services/uid1007/DynamicQuestionAnswering.java - Line 22: package com.wolfram.alpha does not exist \nstring:///net/b07z/sepia/sdk/services/uid1007/DynamicQuestionAnswering.java - Line 23: package com.wolfram.alpha does not exist \nstring:///net/b07z/sepia/sdk/services/uid1007/DynamicQuestionAnswering.java - Line 24: package com.wolfram.alpha does not exist \nstring:///net/b07z/sepia/sdk/services/uid1007/DynamicQuestionAnswering.java - Line 25: package com.wolfram.alpha does not exist \n" `}``

what i am doing wrong? do i have to import the file somewhere else?

sorry i am a total beginner ;)

/roy

**Comment by fquirin** [comment]
Hi roy,

the reason this does not work is because during start of the server the classpath is set to the specific .jar files listed inside the main jar manifest (theoretically you can unzip this file and modify it, but that's another story ^^).

There are a few options to work around this:

1) Personally I'd prefer to load the jar file dynamically inside your smart-service with the `SandboxClassLoader` for more security, but I've not yet tested this myself. I'll try to optimize and document the procedure for the next release.

2) Quick and dirty. Shutdown your SEPIA server then go to your `SEPIA/sepia-assist-server/` folder and look for the `run.sh`. Replace the last line like this:
```
#nohup java -jar -Xms200m -Xmx200m $JAR_NAME --my &> log.out&
nohup java -cp "$JAR_NAME:libs/*" net.b07z.sepia.server.assist.server.Start --my &> log.out&
```
Then place your jar file inside `SEPIA/sepia-assist-server/libs/` and it should theoretically be available after restart. The modified run command will load ALL jar-files from the libs folder instead of just the one mentioned in the original manifest.

Let me know if option 2 worked if you test it 😁

**Comment by royrogermcfreely** [comment]
after i change the lines in the run.sh file i cannot upload any service with the default code.
just gives me just this error:
`{
"result":"fail",
"error":"ERROR: null"}`

the log.out file gives no importend errors

**Comment by fquirin** [comment]
Hmm :-/ did you try any of the demo services?
I'll try to do some tests later myself.

**Comment by royrogermcfreely** [comment]
sorry for the misunderstanding. i tried it with the demo services and they give me all the same error

**Comment by fquirin** [comment]
I did a quick test and noticed that the server failed to properly shutdown because I forgot to adjust the `SEPIA/sepia-assist-server/shutdown.sh` 🤦‍♂️.
Can you please change the last line like this:
```
#pkill -f 'java -jar .*sepia-assist.*'
pkill -f 'java -cp .*sepia-assist.*'
```

Then shutdown the whole server again, restart and try again?

I was able to upload the HelloWorld demo service afterwards including `import com.wolfram.alpha.WAEngine;` in the header (with WolframAlpha-1.1.jar inside SEPIA/sepia-assist-server/libs) 🙂

**Comment by fquirin** [comment]
> do i need to copy the files again or it doesnt matter if they are there from before?

The order doesn't matter as long as everything is set before you start the server. Maybe test with the "check" script before you start the server if the old one was closed properly.

> saw on twitter you working on sepia with homeassistant :) i am looking forward for your work there

Supporting HA was a bit more complicated than I had hoped 😅 , but the basics should work well in the next release :-)

> and try to upload the service with your code i get the following error: ...

There are a few imports missing when you uncomment the code lines:
```
import java.net.URLEncoder;
import org.json.simple.JSONObject;
import net.b07z.sepia.server.core.tools.Connectors;
import net.b07z.sepia.server.core.tools.Debugger;
import net.b07z.sepia.server.core.tools.JSON;
```

This should be it, I think.
Did you restore the old run/shutdown command? Or did you get those errors with the same settings that triggered ` { "result":"fail", "error":"ERROR: null"}` before? That error is really weird somehow 🤔 Which demo service was that?

**Comment by royrogermcfreely** [comment]
i stopped sepia, changed the lines in run.sh and shutdown.sh, placed the files in the lib folder and restartet the machine. 
nothing changed.

no the error just came with the changes in run.sh and shutdown.sh

when i start the checkscript after the shutdown script, i get this:
`sepia       9454    9452  0 19:12 pts/0    00:00:00 grep java.*sepia-assist.*

and after the change and start i get:
```
sepia       9670       1  2 19:15 pts/0    00:00:04 java -cp sepia-assist-v2.6.2.jar:libs/* net.b07z.sepia.server.assist.server.Start --my
sepia      10007   10005  0 19:19 pts/0    00:00:00 grep java.*sepia-assist.*

```
about the http request:
do i have to import something else to open a http request?
i dont get a json, just a string with text so i tried this code:

```
HttpClient client = HttpClient.newHttpClient();
HttpRequest request = HttpRequest.newBuilder()
        .uri(URI.create("https://api.wolframalpha.com/v1/spoken?i=" + qUrlParam))
	.build();
HttpResponse response = client.send(request, HttpResponse.BodyHandlers.ofString());
```

but it fails with:

```
{
  "result": "fail",
  "error": "ERROR: Class 'DynamicQuestionAnswering' - Compile errors: \nstring:///net/b07z/sepia/sdk/services/uid1007/DynamicQuestionAnswering.java - Line 179: cannot find symbol\n  symbol:   class HttpClient\n  location: class net.b07z.sepia.sdk.services.uid1007.DynamicQuestionAnswering \nstring:///net/b07z/sepia/sdk/services/uid1007/DynamicQuestionAnswering.java - Line 179: cannot find symbol\n  symbol:   variable HttpClient\n  location: class net.b07z.sepia.sdk.services.uid1007.DynamicQuestionAnswering \nstring:///net/b07z/sepia/sdk/services/uid1007/DynamicQuestionAnswering.java - Line 180: cannot find symbol\n  symbol:   class HttpRequest\n  location: class net.b07z.sepia.sdk.services.uid1007.DynamicQuestionAnswering \nstring:///net/b07z/sepia/sdk/services/uid1007/DynamicQuestionAnswering.java - Line 180: cannot find symbol\n  symbol:   variable HttpRequest\n  location: class net.b07z.sepia.sdk.services.uid1007.DynamicQuestionAnswering \nstring:///net/b07z/sepia/sdk/services/uid1007/DynamicQuestionAnswering.java - Line 181: cannot find symbol\n  symbol:   variable URI\n  location: class net.b07z.sepia.sdk.services.uid1007.DynamicQuestionAnswering \nstring:///net/b07z/sepia/sdk/services/uid1007/DynamicQuestionAnswering.java - Line 184: cannot find symbol\n  symbol:   class HttpResponse\n  location: class net.b07z.sepia.sdk.services.uid1007.DynamicQuestionAnswering \nstring:///net/b07z/sepia/sdk/services/uid1007/DynamicQuestionAnswering.java - Line 184: package HttpResponse does not exist \n"
}
```

**Comment by fquirin** [comment]
> and after the change and start i get: ...

looks ok. I can't really explain where the error is coming from since I can't seem to be able to reproduce it 🤔 
Is the rest of the server working without errors?

> do i have to import something else to open a http request?
i dont get a json, just a string with text so i tried this code: ...

There are many possible ways to do the HTTP request, I'd recommend to use this one from the "Connectors" package:
```
import java.net.URLEncoder;
import net.b07z.sepia.server.core.tools.Connectors;
import net.b07z.sepia.server.core.tools.Connectors.HttpClientResult;
import net.b07z.sepia.server.core.tools.Debugger;
...
try {
  String url = "https://api.wolframalpha.com/v1/spoken?i=" + URLEncoder.encode(qRaw, "UTF-8");
  String contentType = "text/plain";
  HttpClientResult result = Connectors.apacheHttpGET(url, contentType);
  if (result.statusCode == 200){
	  //the string content
	  Debugger.println("DynamicQuestionAnswering - API response: " + result.content, 3);
	  //you can still parse it if it's JSON:
	  //JSONObject json = JSON.parseStringOrFail(result.content);
  }else{
	  //error
	  Debugger.println("DynamicQuestionAnswering - failed to call API - Error: " + result.statusCode + " - " + result.statusLine, 1);
  }
}catch (Exception e){
  Debugger.println("DynamicQuestionAnswering - failed to call API - Error: " + e.getMessage(), 1);
}
```

If you need to change the request headers there is a version with headers map as well: `apacheHttpGET(String url, Map<String, String> headers)`.

If you need more customizations you can check out the [given implementation](https://github.com/SEPIA-Framework/sepia-core-tools-java/blob/master/src/main/java/net/b07z/sepia/server/core/tools/Connectors.java#L221) and look-up the imports in the class header.

**Comment by royrogermcfreely** [comment]
Hey,

i was playing arround with the wolfram service again and i have another question:

the http request from above for wolframalpha is working.

now i try to translate the language, for that i got an api key from deepL.com. 
there i get a jsonarray back like 
``
{"translations":[{"detected_source_language":"DE","text":"how high is the eiffel tower"}]}
``
when i uncommend 
``
	  //you can still parse it if it's JSON: 
	  //JSONObject json = JSON.parseStringOrFail(result.content);
``
i get this error:
``
Line 209: cannot find symbol\n  symbol:   method parseStringorFail(java.lang.String)\n  location: class net.b07z.sepia.server.core.tools.JSON \nstring:///net/b07z/sepia/sdk/services/uid1007/DynamicQuestionAnswering.java - 
``

i tried it with "import org.json.simple.JSONArray;" too but same error.

do i have to load some extra jars for working with json?

/roy

**Comment by royrogermcfreely** [comment]
Hey,

got it working :)

created an new discussion for it ->[ WolframAlpha SmartSevices](https://github.com/SEPIA-Framework/sepia-docs/discussions/226)

/roy
