### ISSUE TITLE
Can't seem to get SEPIA working :(

### ISSUE THREAD

**Issue by EmonFan** [SEPIA-Framework/sepia-docs#4]
Hi, I've tried the latest releases in both a docker container and from a fresh ubuntu installation in a virtual machine. Everything compiles(docker) or everything installs correctly on the vm but whenever I try to start SEPIA I always get the following:
`---- Testing cluster ----
-----Assist API-----
curl: (7) Failed to connect to localhost port 20721: Connection refused
-----Teach API-----
curl: (7) Failed to connect to localhost port 20722: Connection refused
-----Chat API - WebSocket Server-----
curl: (7) Failed to connect to localhost port 20723: Connection refused
`
Obviously, I can't access this instance from another machine.
Where should I start looking to figure out the issue?
Thanks

**Comment by fquirin** [comment]
Sorry I saw your message just now.
I'll have a closer look again tomorrow but could you check the log file of the assist server to see if there is any additional info? I wonder if there might be a firewall blocking the ports.

**Comment by EmonFan** [comment]
Hi, all working now with JAXB dependencies resolved. I also fixed the
dockerfile if you are interested. the debian:jesse doesn't compile. ubuntu
does. I'll be getting more familiar with your code now that I have a
working base.
cheers. we

**Comment by fquirin** [comment]
Hi, good to hear it's working now. I've setup a new test-system to investigate Java 9 issues there might be buried more than I initially recognized.
I'd definitely be interested to see your Dockerfile changes, could you post them here?

**Comment by EmonFan** [comment]
Hi Florian, the simplest change to the docker file is to simply replace
FROM debian:jesse to
FROM ubuntu:16.04
or
FROM ubuntu:18.04
That's all. I haven't played with any other parameters but this allows the
docker file to build and run.
The Debian:Jesse image doesn't work for me. My docker host is Ubuntu.

Marc.

**Comment by fquirin** [comment]
Hi Marc,

thanks for the info. It is kind of weird though because the whole point of Docker is to not need to build a new container for every platform =)
Could you point me to the Dockerfile you are using? Usually the SEPIA containers start with "debian:stretch-slim", like:
https://github.com/SEPIA-Framework/sepia-installation-and-setup/blob/master/Dockerfile

**Comment by EmonFan** [comment]
Hi Florian, that’s the docke file I’m using. It does not compile on my
system.
Ubuntu 18.04 (server) host with latest Docker-ce installed. (Fresh
installation)
 I’m just starting out with Docker, but it’s amazing technology.

The only modification to your Dockerfile is to replace FROM Debian:(any
version) with FROM ubuntu:16.04 (or 18.04)
Everything else is untouched.

What host os are you using? Does it complie for you?

BTW I played around a little bit with a microphone and I’m pretty
enthusiastic about diving in and getting familiar with your framework. I
think there is a lot of potential here.

Good job!

**Comment by EmonFan** [comment]
Oops, My host is Ubuntu 16.04, not 18.04.
I’m playing around with Deepspeech via Docker on this host also.

**Comment by fquirin** [comment]
Hi Marc,
happy you like it :-)

I've compiled the file inside a docker container that was running Debian 9 so I guess it makes sense that it worked ^^. For the next version of SEPIA-Home (2.2.0) I'll probably upload a pre-compiled image to DockerHub (https://hub.docker.com/u/sepia) ... after all people should not need to compile it themselves ;-)

About Deepspeech. Actually I'm very excited about it and I'm following the development, but I've not yet included it into the SEPIA framework because it's much more resource intense and more complicated to handle (at least that was my impression). I'd be happy to see anything that is compatible to SEPIA though :-D

**Comment by pulkitj79** [comment]
Hi, 

I am not able to run SEPIA server with same error as reported by @EmonFan .

FYI: I am running Docker on Windows and that seems to complicate the issue.

regards,

**Comment by fquirin** [comment]
Hi,

I'm running Docker on Windows too from time to time ... usually not a problem,
I've also fixed Java 9 related issues in v2.2.0 (https://github.com/SEPIA-Framework/sepia-installation-and-setup/releases) so I guess the fix above is not working for you either?

The error 'Failed to connect to localhost' can have many reasons. Usually it means that the server can't be reached (due to firewall reasons etc.) or that it did not even start at all (error or blocked ports?).

Have you checked all log files, especially inside sepia-assist-server (log.out) and tried to ping the servers from localhost? The Control HUB (http://localhost:20721/tools/index.html) can help you with that too.
