### ISSUE TITLE
Locked out 

### ISSUE THREAD

**Issue by Xsafiqe** [SEPIA-Framework/sepia-docs#46]
Hi there, 

So I installed SEPIA to use it with my Openhab. Today I edited some user roles in the User Management Settings. 
I accidentally gave my Admin User the role "smarthomguest" and now I don't have any permissions at all! 

Is there a way to reset SEPIA itself or create a new Administrator? 

Thank's in advance!

**Comment by fquirin** [comment]
Hi,

can you describe how exactly you've managed to change the roles of the admin account? Because they are write protected 😅.

Are you sure it was uid1003 you've edited? Trying to change the admin or assistant account roles usually triggers the error message "cannot edit core user roles".

It is possible to reset the admin account via a script in the SEPIA folder but I'd prefer to find out first what happened 🙂.

**Comment by Xsafiqe** [comment]
Thank's for the fast reply 😊

I just managed to fix it myself 🙂


I really don't know how I managed to change the role... I did it just like I said in the first thread. 🤔
