### ISSUE TITLE
Strong American Accent with German Language for TTS on Samsung J4+

### ISSUE THREAD

**Issue by jlemmer** [SEPIA-Framework/sepia-docs#48]
Hi again,

after Sepia is working at my house now I asked my son to install the app on his mobile, too. Installation was flawless, but there is a curious bug: Although language is set to German with voice output using the native engine and the system voice the voice of the mobile differs extremly from my mobile. There is a very strong american Accent on every voice output whereas my Samsung S8 has a clear German voice. I am not quite sure if this is a Sepia problem at all, but perhaps you might have an idea what to alter to get a clear voice on the J4+, too.

**Comment by fquirin** [comment]
Hi,

its interesting since both are Samsung phones, but my best guess is that the J4 has a different system setting. In my Samsung this can be found at "Allgemeine Verwaltung -> Sprache und Eingabe -> Text-zu-Sprache".
Another option is to change the TTS engine in SEPIA using voices generated by the SEPIA server. Depending on your server setup there should be a hand full of voices available for German and English. They sound much more robotic though, but I like the "eSpeak" version ;-)

**Comment by jlemmer** [comment]
Thanks for quick reply, I will check out with my son after he is back from school.

**Comment by jlemmer** [comment]
You were right! It was a parameter in the general settings of the mobile. Whereas my S8 uses Google TTS as a default (cannot remember to change anything), the J4+ was using Samsung TTS. After changing it to Google, too, the accent is gone now. Thanks!
