### ISSUE TITLE
Graceful logout from multi-session

### ISSUE THREAD

**Issue by farrad** [SEPIA-Framework/sepia-docs#6]
Hi Florian,

thanks for the interesting project!
I have a question:

**Usecase:** I log in from a third-party client while being previously logged in from the SEPIA WebClient (under the same uid), and then logout from the third-party client (simply close websocket).
**Observation:** I see in the chat window the following messages:

> SEPIA-Websocket-Server: Your session is now inactive in channel (***) until you send a message
> SEPIA-Websocket-Server: *** (***) joined the chat
> SEPIA-Websocket-Server: *** (***) left the chat

Then if I try to send messages to the chat from the WebClient, which was deactivated I get:

> Sepia: Login? Error?

If I try the same usecase with two WebClients it works (initial session is re-activated).

**Question:** If my understanding is correct simply closing websocket is not enough to gracefully close the session (another session can be reactivated). Am I missing something?
What are the correct steps to close/re-activate the session?

**Comment by farrad** [comment]
It is solved for me after SSL was enabled.

**Comment by fquirin** [comment]
Hi farrad, sorry for the late reply and happy to hear that you could solve the problem. Though I wonder how this issue was related to SSL. 
The usualy process is that the client automatically activates again if you send a message. Btw there is also a device ID (web-app -> settings) that can be used to distinguish the clients when you login with the same account, though the Websocket server might not fully support it yet.
