### ISSUE TITLE
SEPIA app for Android requirements.

### ISSUE THREAD

**Issue by MrTheBarbarian** [SEPIA-Framework/sepia-docs#89]
Hello!
I would like to ask you about requirements for the Android version and hardware for installing the SEPIA APP.
I have Samsung Note 8 with Android 9 and XIAOMI redmi note 9 pro with Android 10. I can't install the app to them from the google store, because  those phones do not support it.
Thanks!

**Comment by fquirin** [comment]
Hi,

so this is strange because Samsung Note 8 should definitely work :thinking: 
The requirements are very low, even Android 4.4 is still supported.
Have you tried side-loading the APK file that you can download on the [release page](https://github.com/SEPIA-Framework/sepia-installation-and-setup/releases) (after the intro or at the bottom in the "assets" section)?

**Comment by MrTheBarbarian** [comment]
Hi! The apps is working! Thanks! It have to download from release page.
